server {
    listen 80;
    server_name _;

    # Let's Encrypt ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # En prod : décommenter pour forcer HTTPS
    # return 301 https://$host$request_uri;

    root /var/www/html/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location /admin {
        try_files $uri $uri/ /admin/login.php?$query_string;
    }

    location ~ \.php$ {
        resolver 127.0.0.11 valid=10s;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
}

# Décommenter après SSL Let's Encrypt
# server {
#     listen 443 ssl;
#     server_name votre-domaine.fr;
#     ssl_certificate /etc/letsencrypt/live/votre-domaine.fr/fullchain.pem;
#     ssl_certificate_key /etc/letsencrypt/live/votre-domaine.fr/privkey.pem;
#     root /var/www/html/public;
#     index index.php;
#     location / { try_files $uri $uri/ /index.php?$query_string; }
#     location ~ \.php$ {
        resolver 127.0.0.11 valid=10s;
#         fastcgi_pass app:9000;
#         fastcgi_param SCRIPT_FILENAME /var/www/html/public$fastcgi_script_name;
#         include fastcgi_params;
#     }
# }
